enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.20.13

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.40.cjs
