packageExtensions:
  "@mui/core@*":
    dependencies:
      "@mui/system": ^5.3.0
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/styled": ^11.6.0
  argon2@*:
    dependencies:
      node-gyp: ^8.4.1
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.16.7

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0-rc.12.cjs
