packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.12.5
  relay-compiler@*:
    dependencies:
      relay-compiler-language-typescript: ^13.0.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-bundle.cjs
    spec: "https://yarnplugins.com/bundle"
  - path: .yarn/plugins/@yarnpkg/plugin-push.cjs
    spec: "https://yarnplugins.com/push"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
