// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.user_role */
enum UserRole {
  owner = 'owner',
  member = 'member',
};

export default UserRole;

/** Zod schema for user_role */
export const userRole = z.enum([
  'owner',
  'member',
]);;
