// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { workspaceId, type WorkspaceId } from './Workspace';
import { userId, type UserId } from './User';
import { userRole, type default as UserRole } from './UserRole';
import { z } from 'zod';

/** Represents the table public.workspace_member */
export default interface WorkspaceMember {
  workspace_id: WorkspaceId;

  user_id: UserId;

  role: UserRole;
}

/** Represents the initializer for the table public.workspace_member */
export interface WorkspaceMemberInitializer {
  workspace_id: WorkspaceId;

  user_id: UserId;

  /** Default value: 'member'::user_role */
  role?: UserRole;
}

/** Represents the mutator for the table public.workspace_member */
export interface WorkspaceMemberMutator {
  workspace_id?: WorkspaceId;

  user_id?: UserId;

  role?: UserRole;
}

export const workspaceMember = z.object({
  workspace_id: workspaceId,
  user_id: userId,
  role: userRole,
}) as unknown as z.Schema<WorkspaceMember>;

export const workspaceMemberInitializer = z.object({
  workspace_id: workspaceId,
  user_id: userId,
  role: userRole.optional(),
}) as unknown as z.Schema<WorkspaceMemberInitializer>;

export const workspaceMemberMutator = z.object({
  workspace_id: workspaceId.optional(),
  user_id: userId.optional(),
  role: userRole.optional(),
}) as unknown as z.Schema<WorkspaceMemberMutator>;
